// source: chat.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

goog.exportSymbol('proto.chat.Kullanici', null, global);
goog.exportSymbol('proto.chat.Mesaj', null, global);
goog.exportSymbol('proto.chat.MesajGonderIstek', null, global);
goog.exportSymbol('proto.chat.MesajGonderYanit', null, global);
goog.exportSymbol('proto.chat.MesajTipi', null, global);
goog.exportSymbol('proto.chat.SohbetiDinleIstek', null, global);
goog.exportSymbol('proto.chat.YaziyorDurumuIstek', null, global);
goog.exportSymbol('proto.chat.YaziyorDurumuYanit', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.chat.Kullanici = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.chat.Kullanici, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.chat.Kullanici.displayName = 'proto.chat.Kullanici';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.chat.Mesaj = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.chat.Mesaj, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.chat.Mesaj.displayName = 'proto.chat.Mesaj';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.chat.MesajGonderIstek = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.chat.MesajGonderIstek, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.chat.MesajGonderIstek.displayName = 'proto.chat.MesajGonderIstek';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.chat.MesajGonderYanit = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.chat.MesajGonderYanit, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.chat.MesajGonderYanit.displayName = 'proto.chat.MesajGonderYanit';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.chat.SohbetiDinleIstek = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.chat.SohbetiDinleIstek, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.chat.SohbetiDinleIstek.displayName = 'proto.chat.SohbetiDinleIstek';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.chat.YaziyorDurumuIstek = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.chat.YaziyorDurumuIstek, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.chat.YaziyorDurumuIstek.displayName = 'proto.chat.YaziyorDurumuIstek';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.chat.YaziyorDurumuYanit = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.chat.YaziyorDurumuYanit, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.chat.YaziyorDurumuYanit.displayName = 'proto.chat.YaziyorDurumuYanit';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.chat.Kullanici.prototype.toObject = function(opt_includeInstance) {
  return proto.chat.Kullanici.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.chat.Kullanici} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.chat.Kullanici.toObject = function(includeInstance, msg) {
  var f, obj = {
id: jspb.Message.getFieldWithDefault(msg, 1, ""),
ad: jspb.Message.getFieldWithDefault(msg, 2, ""),
avatarUrl: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.chat.Kullanici}
 */
proto.chat.Kullanici.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.chat.Kullanici;
  return proto.chat.Kullanici.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.chat.Kullanici} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.chat.Kullanici}
 */
proto.chat.Kullanici.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setAd(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setAvatarUrl(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.chat.Kullanici.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.chat.Kullanici.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.chat.Kullanici} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.chat.Kullanici.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAd();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getAvatarUrl();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.chat.Kullanici.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.chat.Kullanici} returns this
 */
proto.chat.Kullanici.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string ad = 2;
 * @return {string}
 */
proto.chat.Kullanici.prototype.getAd = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.chat.Kullanici} returns this
 */
proto.chat.Kullanici.prototype.setAd = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string avatar_url = 3;
 * @return {string}
 */
proto.chat.Kullanici.prototype.getAvatarUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.chat.Kullanici} returns this
 */
proto.chat.Kullanici.prototype.setAvatarUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.chat.Mesaj.prototype.toObject = function(opt_includeInstance) {
  return proto.chat.Mesaj.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.chat.Mesaj} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.chat.Mesaj.toObject = function(includeInstance, msg) {
  var f, obj = {
id: jspb.Message.getFieldWithDefault(msg, 1, ""),
kullanici: (f = msg.getKullanici()) && proto.chat.Kullanici.toObject(includeInstance, f),
icerik: jspb.Message.getFieldWithDefault(msg, 3, ""),
tip: jspb.Message.getFieldWithDefault(msg, 4, 0),
zaman: jspb.Message.getFieldWithDefault(msg, 5, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.chat.Mesaj}
 */
proto.chat.Mesaj.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.chat.Mesaj;
  return proto.chat.Mesaj.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.chat.Mesaj} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.chat.Mesaj}
 */
proto.chat.Mesaj.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = new proto.chat.Kullanici;
      reader.readMessage(value,proto.chat.Kullanici.deserializeBinaryFromReader);
      msg.setKullanici(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setIcerik(value);
      break;
    case 4:
      var value = /** @type {!proto.chat.MesajTipi} */ (reader.readEnum());
      msg.setTip(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setZaman(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.chat.Mesaj.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.chat.Mesaj.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.chat.Mesaj} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.chat.Mesaj.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getKullanici();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.chat.Kullanici.serializeBinaryToWriter
    );
  }
  f = message.getIcerik();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getTip();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
  f = message.getZaman();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.chat.Mesaj.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.chat.Mesaj} returns this
 */
proto.chat.Mesaj.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional Kullanici kullanici = 2;
 * @return {?proto.chat.Kullanici}
 */
proto.chat.Mesaj.prototype.getKullanici = function() {
  return /** @type{?proto.chat.Kullanici} */ (
    jspb.Message.getWrapperField(this, proto.chat.Kullanici, 2));
};


/**
 * @param {?proto.chat.Kullanici|undefined} value
 * @return {!proto.chat.Mesaj} returns this
*/
proto.chat.Mesaj.prototype.setKullanici = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.chat.Mesaj} returns this
 */
proto.chat.Mesaj.prototype.clearKullanici = function() {
  return this.setKullanici(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.chat.Mesaj.prototype.hasKullanici = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string icerik = 3;
 * @return {string}
 */
proto.chat.Mesaj.prototype.getIcerik = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.chat.Mesaj} returns this
 */
proto.chat.Mesaj.prototype.setIcerik = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional MesajTipi tip = 4;
 * @return {!proto.chat.MesajTipi}
 */
proto.chat.Mesaj.prototype.getTip = function() {
  return /** @type {!proto.chat.MesajTipi} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {!proto.chat.MesajTipi} value
 * @return {!proto.chat.Mesaj} returns this
 */
proto.chat.Mesaj.prototype.setTip = function(value) {
  return jspb.Message.setProto3EnumField(this, 4, value);
};


/**
 * optional int64 zaman = 5;
 * @return {number}
 */
proto.chat.Mesaj.prototype.getZaman = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.chat.Mesaj} returns this
 */
proto.chat.Mesaj.prototype.setZaman = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.chat.MesajGonderIstek.prototype.toObject = function(opt_includeInstance) {
  return proto.chat.MesajGonderIstek.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.chat.MesajGonderIstek} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.chat.MesajGonderIstek.toObject = function(includeInstance, msg) {
  var f, obj = {
mesaj: (f = msg.getMesaj()) && proto.chat.Mesaj.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.chat.MesajGonderIstek}
 */
proto.chat.MesajGonderIstek.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.chat.MesajGonderIstek;
  return proto.chat.MesajGonderIstek.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.chat.MesajGonderIstek} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.chat.MesajGonderIstek}
 */
proto.chat.MesajGonderIstek.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.chat.Mesaj;
      reader.readMessage(value,proto.chat.Mesaj.deserializeBinaryFromReader);
      msg.setMesaj(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.chat.MesajGonderIstek.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.chat.MesajGonderIstek.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.chat.MesajGonderIstek} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.chat.MesajGonderIstek.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMesaj();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.chat.Mesaj.serializeBinaryToWriter
    );
  }
};


/**
 * optional Mesaj mesaj = 1;
 * @return {?proto.chat.Mesaj}
 */
proto.chat.MesajGonderIstek.prototype.getMesaj = function() {
  return /** @type{?proto.chat.Mesaj} */ (
    jspb.Message.getWrapperField(this, proto.chat.Mesaj, 1));
};


/**
 * @param {?proto.chat.Mesaj|undefined} value
 * @return {!proto.chat.MesajGonderIstek} returns this
*/
proto.chat.MesajGonderIstek.prototype.setMesaj = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.chat.MesajGonderIstek} returns this
 */
proto.chat.MesajGonderIstek.prototype.clearMesaj = function() {
  return this.setMesaj(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.chat.MesajGonderIstek.prototype.hasMesaj = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.chat.MesajGonderYanit.prototype.toObject = function(opt_includeInstance) {
  return proto.chat.MesajGonderYanit.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.chat.MesajGonderYanit} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.chat.MesajGonderYanit.toObject = function(includeInstance, msg) {
  var f, obj = {
basarili: jspb.Message.getBooleanFieldWithDefault(msg, 1, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.chat.MesajGonderYanit}
 */
proto.chat.MesajGonderYanit.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.chat.MesajGonderYanit;
  return proto.chat.MesajGonderYanit.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.chat.MesajGonderYanit} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.chat.MesajGonderYanit}
 */
proto.chat.MesajGonderYanit.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setBasarili(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.chat.MesajGonderYanit.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.chat.MesajGonderYanit.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.chat.MesajGonderYanit} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.chat.MesajGonderYanit.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBasarili();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
};


/**
 * optional bool basarili = 1;
 * @return {boolean}
 */
proto.chat.MesajGonderYanit.prototype.getBasarili = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.chat.MesajGonderYanit} returns this
 */
proto.chat.MesajGonderYanit.prototype.setBasarili = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.chat.SohbetiDinleIstek.prototype.toObject = function(opt_includeInstance) {
  return proto.chat.SohbetiDinleIstek.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.chat.SohbetiDinleIstek} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.chat.SohbetiDinleIstek.toObject = function(includeInstance, msg) {
  var f, obj = {
odaId: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.chat.SohbetiDinleIstek}
 */
proto.chat.SohbetiDinleIstek.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.chat.SohbetiDinleIstek;
  return proto.chat.SohbetiDinleIstek.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.chat.SohbetiDinleIstek} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.chat.SohbetiDinleIstek}
 */
proto.chat.SohbetiDinleIstek.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setOdaId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.chat.SohbetiDinleIstek.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.chat.SohbetiDinleIstek.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.chat.SohbetiDinleIstek} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.chat.SohbetiDinleIstek.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOdaId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string oda_id = 1;
 * @return {string}
 */
proto.chat.SohbetiDinleIstek.prototype.getOdaId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.chat.SohbetiDinleIstek} returns this
 */
proto.chat.SohbetiDinleIstek.prototype.setOdaId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.chat.YaziyorDurumuIstek.prototype.toObject = function(opt_includeInstance) {
  return proto.chat.YaziyorDurumuIstek.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.chat.YaziyorDurumuIstek} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.chat.YaziyorDurumuIstek.toObject = function(includeInstance, msg) {
  var f, obj = {
odaId: jspb.Message.getFieldWithDefault(msg, 1, ""),
kullanici: (f = msg.getKullanici()) && proto.chat.Kullanici.toObject(includeInstance, f),
yaziyor: jspb.Message.getBooleanFieldWithDefault(msg, 3, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.chat.YaziyorDurumuIstek}
 */
proto.chat.YaziyorDurumuIstek.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.chat.YaziyorDurumuIstek;
  return proto.chat.YaziyorDurumuIstek.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.chat.YaziyorDurumuIstek} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.chat.YaziyorDurumuIstek}
 */
proto.chat.YaziyorDurumuIstek.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setOdaId(value);
      break;
    case 2:
      var value = new proto.chat.Kullanici;
      reader.readMessage(value,proto.chat.Kullanici.deserializeBinaryFromReader);
      msg.setKullanici(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setYaziyor(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.chat.YaziyorDurumuIstek.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.chat.YaziyorDurumuIstek.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.chat.YaziyorDurumuIstek} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.chat.YaziyorDurumuIstek.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOdaId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getKullanici();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.chat.Kullanici.serializeBinaryToWriter
    );
  }
  f = message.getYaziyor();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
};


/**
 * optional string oda_id = 1;
 * @return {string}
 */
proto.chat.YaziyorDurumuIstek.prototype.getOdaId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.chat.YaziyorDurumuIstek} returns this
 */
proto.chat.YaziyorDurumuIstek.prototype.setOdaId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional Kullanici kullanici = 2;
 * @return {?proto.chat.Kullanici}
 */
proto.chat.YaziyorDurumuIstek.prototype.getKullanici = function() {
  return /** @type{?proto.chat.Kullanici} */ (
    jspb.Message.getWrapperField(this, proto.chat.Kullanici, 2));
};


/**
 * @param {?proto.chat.Kullanici|undefined} value
 * @return {!proto.chat.YaziyorDurumuIstek} returns this
*/
proto.chat.YaziyorDurumuIstek.prototype.setKullanici = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.chat.YaziyorDurumuIstek} returns this
 */
proto.chat.YaziyorDurumuIstek.prototype.clearKullanici = function() {
  return this.setKullanici(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.chat.YaziyorDurumuIstek.prototype.hasKullanici = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional bool yaziyor = 3;
 * @return {boolean}
 */
proto.chat.YaziyorDurumuIstek.prototype.getYaziyor = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.chat.YaziyorDurumuIstek} returns this
 */
proto.chat.YaziyorDurumuIstek.prototype.setYaziyor = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.chat.YaziyorDurumuYanit.prototype.toObject = function(opt_includeInstance) {
  return proto.chat.YaziyorDurumuYanit.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.chat.YaziyorDurumuYanit} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.chat.YaziyorDurumuYanit.toObject = function(includeInstance, msg) {
  var f, obj = {
basarili: jspb.Message.getBooleanFieldWithDefault(msg, 1, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.chat.YaziyorDurumuYanit}
 */
proto.chat.YaziyorDurumuYanit.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.chat.YaziyorDurumuYanit;
  return proto.chat.YaziyorDurumuYanit.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.chat.YaziyorDurumuYanit} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.chat.YaziyorDurumuYanit}
 */
proto.chat.YaziyorDurumuYanit.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setBasarili(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.chat.YaziyorDurumuYanit.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.chat.YaziyorDurumuYanit.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.chat.YaziyorDurumuYanit} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.chat.YaziyorDurumuYanit.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBasarili();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
};


/**
 * optional bool basarili = 1;
 * @return {boolean}
 */
proto.chat.YaziyorDurumuYanit.prototype.getBasarili = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.chat.YaziyorDurumuYanit} returns this
 */
proto.chat.YaziyorDurumuYanit.prototype.setBasarili = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * @enum {number}
 */
proto.chat.MesajTipi = {
  METIN: 0,
  SISTEM: 1,
  YAZIYOR: 2
};

goog.object.extend(exports, proto.chat);
