/**
 * @fileoverview gRPC-Web generated client stub for chat
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v7.34.1
// source: chat.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.chat = require('./chat_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.chat.ChatServisClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.chat.ChatServisPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.chat.MesajGonderIstek,
 *   !proto.chat.MesajGonderYanit>}
 */
const methodDescriptor_ChatServis_MesajGonder = new grpc.web.MethodDescriptor(
  '/chat.ChatServis/MesajGonder',
  grpc.web.MethodType.UNARY,
  proto.chat.MesajGonderIstek,
  proto.chat.MesajGonderYanit,
  /**
   * @param {!proto.chat.MesajGonderIstek} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.chat.MesajGonderYanit.deserializeBinary
);


/**
 * @param {!proto.chat.MesajGonderIstek} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.chat.MesajGonderYanit)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.chat.MesajGonderYanit>|undefined}
 *     The XHR Node Readable Stream
 */
proto.chat.ChatServisClient.prototype.mesajGonder =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/chat.ChatServis/MesajGonder',
      request,
      metadata || {},
      methodDescriptor_ChatServis_MesajGonder,
      callback);
};


/**
 * @param {!proto.chat.MesajGonderIstek} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.chat.MesajGonderYanit>}
 *     Promise that resolves to the response
 */
proto.chat.ChatServisPromiseClient.prototype.mesajGonder =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/chat.ChatServis/MesajGonder',
      request,
      metadata || {},
      methodDescriptor_ChatServis_MesajGonder);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.chat.SohbetiDinleIstek,
 *   !proto.chat.Mesaj>}
 */
const methodDescriptor_ChatServis_SohbetiDinle = new grpc.web.MethodDescriptor(
  '/chat.ChatServis/SohbetiDinle',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.chat.SohbetiDinleIstek,
  proto.chat.Mesaj,
  /**
   * @param {!proto.chat.SohbetiDinleIstek} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.chat.Mesaj.deserializeBinary
);


/**
 * @param {!proto.chat.SohbetiDinleIstek} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.chat.Mesaj>}
 *     The XHR Node Readable Stream
 */
proto.chat.ChatServisClient.prototype.sohbetiDinle =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/chat.ChatServis/SohbetiDinle',
      request,
      metadata || {},
      methodDescriptor_ChatServis_SohbetiDinle);
};


/**
 * @param {!proto.chat.SohbetiDinleIstek} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.chat.Mesaj>}
 *     The XHR Node Readable Stream
 */
proto.chat.ChatServisPromiseClient.prototype.sohbetiDinle =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/chat.ChatServis/SohbetiDinle',
      request,
      metadata || {},
      methodDescriptor_ChatServis_SohbetiDinle);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.chat.YaziyorDurumuIstek,
 *   !proto.chat.YaziyorDurumuYanit>}
 */
const methodDescriptor_ChatServis_YaziyorDurumuGuncelle = new grpc.web.MethodDescriptor(
  '/chat.ChatServis/YaziyorDurumuGuncelle',
  grpc.web.MethodType.UNARY,
  proto.chat.YaziyorDurumuIstek,
  proto.chat.YaziyorDurumuYanit,
  /**
   * @param {!proto.chat.YaziyorDurumuIstek} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.chat.YaziyorDurumuYanit.deserializeBinary
);


/**
 * @param {!proto.chat.YaziyorDurumuIstek} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.chat.YaziyorDurumuYanit)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.chat.YaziyorDurumuYanit>|undefined}
 *     The XHR Node Readable Stream
 */
proto.chat.ChatServisClient.prototype.yaziyorDurumuGuncelle =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/chat.ChatServis/YaziyorDurumuGuncelle',
      request,
      metadata || {},
      methodDescriptor_ChatServis_YaziyorDurumuGuncelle,
      callback);
};


/**
 * @param {!proto.chat.YaziyorDurumuIstek} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.chat.YaziyorDurumuYanit>}
 *     Promise that resolves to the response
 */
proto.chat.ChatServisPromiseClient.prototype.yaziyorDurumuGuncelle =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/chat.ChatServis/YaziyorDurumuGuncelle',
      request,
      metadata || {},
      methodDescriptor_ChatServis_YaziyorDurumuGuncelle);
};


module.exports = proto.chat;

