// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: chat.proto

package chat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MesajTipi int32

const (
	MesajTipi_METIN   MesajTipi = 0
	MesajTipi_SISTEM  MesajTipi = 1
	MesajTipi_YAZIYOR MesajTipi = 2
)

// Enum value maps for MesajTipi.
var (
	MesajTipi_name = map[int32]string{
		0: "METIN",
		1: "SISTEM",
		2: "YAZIYOR",
	}
	MesajTipi_value = map[string]int32{
		"METIN":   0,
		"SISTEM":  1,
		"YAZIYOR": 2,
	}
)

func (x MesajTipi) Enum() *MesajTipi {
	p := new(MesajTipi)
	*p = x
	return p
}

func (x MesajTipi) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MesajTipi) Descriptor() protoreflect.EnumDescriptor {
	return file_chat_proto_enumTypes[0].Descriptor()
}

func (MesajTipi) Type() protoreflect.EnumType {
	return &file_chat_proto_enumTypes[0]
}

func (x MesajTipi) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MesajTipi.Descriptor instead.
func (MesajTipi) EnumDescriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{0}
}

type Kullanici struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ad            string                 `protobuf:"bytes,2,opt,name=ad,proto3" json:"ad,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Kullanici) Reset() {
	*x = Kullanici{}
	mi := &file_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Kullanici) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kullanici) ProtoMessage() {}

func (x *Kullanici) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kullanici.ProtoReflect.Descriptor instead.
func (*Kullanici) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{0}
}

func (x *Kullanici) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Kullanici) GetAd() string {
	if x != nil {
		return x.Ad
	}
	return ""
}

func (x *Kullanici) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type Mesaj struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kullanici     *Kullanici             `protobuf:"bytes,2,opt,name=kullanici,proto3" json:"kullanici,omitempty"`
	Icerik        string                 `protobuf:"bytes,3,opt,name=icerik,proto3" json:"icerik,omitempty"`
	Tip           MesajTipi              `protobuf:"varint,4,opt,name=tip,proto3,enum=chat.MesajTipi" json:"tip,omitempty"`
	Zaman         int64                  `protobuf:"varint,5,opt,name=zaman,proto3" json:"zaman,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mesaj) Reset() {
	*x = Mesaj{}
	mi := &file_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mesaj) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mesaj) ProtoMessage() {}

func (x *Mesaj) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mesaj.ProtoReflect.Descriptor instead.
func (*Mesaj) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{1}
}

func (x *Mesaj) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Mesaj) GetKullanici() *Kullanici {
	if x != nil {
		return x.Kullanici
	}
	return nil
}

func (x *Mesaj) GetIcerik() string {
	if x != nil {
		return x.Icerik
	}
	return ""
}

func (x *Mesaj) GetTip() MesajTipi {
	if x != nil {
		return x.Tip
	}
	return MesajTipi_METIN
}

func (x *Mesaj) GetZaman() int64 {
	if x != nil {
		return x.Zaman
	}
	return 0
}

type MesajGonderIstek struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mesaj         *Mesaj                 `protobuf:"bytes,1,opt,name=mesaj,proto3" json:"mesaj,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MesajGonderIstek) Reset() {
	*x = MesajGonderIstek{}
	mi := &file_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MesajGonderIstek) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MesajGonderIstek) ProtoMessage() {}

func (x *MesajGonderIstek) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MesajGonderIstek.ProtoReflect.Descriptor instead.
func (*MesajGonderIstek) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{2}
}

func (x *MesajGonderIstek) GetMesaj() *Mesaj {
	if x != nil {
		return x.Mesaj
	}
	return nil
}

type MesajGonderYanit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Basarili      bool                   `protobuf:"varint,1,opt,name=basarili,proto3" json:"basarili,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MesajGonderYanit) Reset() {
	*x = MesajGonderYanit{}
	mi := &file_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MesajGonderYanit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MesajGonderYanit) ProtoMessage() {}

func (x *MesajGonderYanit) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MesajGonderYanit.ProtoReflect.Descriptor instead.
func (*MesajGonderYanit) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{3}
}

func (x *MesajGonderYanit) GetBasarili() bool {
	if x != nil {
		return x.Basarili
	}
	return false
}

type SohbetiDinleIstek struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OdaId         string                 `protobuf:"bytes,1,opt,name=oda_id,json=odaId,proto3" json:"oda_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SohbetiDinleIstek) Reset() {
	*x = SohbetiDinleIstek{}
	mi := &file_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SohbetiDinleIstek) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SohbetiDinleIstek) ProtoMessage() {}

func (x *SohbetiDinleIstek) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SohbetiDinleIstek.ProtoReflect.Descriptor instead.
func (*SohbetiDinleIstek) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{4}
}

func (x *SohbetiDinleIstek) GetOdaId() string {
	if x != nil {
		return x.OdaId
	}
	return ""
}

type YaziyorDurumuIstek struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OdaId         string                 `protobuf:"bytes,1,opt,name=oda_id,json=odaId,proto3" json:"oda_id,omitempty"`
	Kullanici     *Kullanici             `protobuf:"bytes,2,opt,name=kullanici,proto3" json:"kullanici,omitempty"`
	Yaziyor       bool                   `protobuf:"varint,3,opt,name=yaziyor,proto3" json:"yaziyor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YaziyorDurumuIstek) Reset() {
	*x = YaziyorDurumuIstek{}
	mi := &file_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YaziyorDurumuIstek) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YaziyorDurumuIstek) ProtoMessage() {}

func (x *YaziyorDurumuIstek) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YaziyorDurumuIstek.ProtoReflect.Descriptor instead.
func (*YaziyorDurumuIstek) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{5}
}

func (x *YaziyorDurumuIstek) GetOdaId() string {
	if x != nil {
		return x.OdaId
	}
	return ""
}

func (x *YaziyorDurumuIstek) GetKullanici() *Kullanici {
	if x != nil {
		return x.Kullanici
	}
	return nil
}

func (x *YaziyorDurumuIstek) GetYaziyor() bool {
	if x != nil {
		return x.Yaziyor
	}
	return false
}

type YaziyorDurumuYanit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Basarili      bool                   `protobuf:"varint,1,opt,name=basarili,proto3" json:"basarili,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YaziyorDurumuYanit) Reset() {
	*x = YaziyorDurumuYanit{}
	mi := &file_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YaziyorDurumuYanit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YaziyorDurumuYanit) ProtoMessage() {}

func (x *YaziyorDurumuYanit) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YaziyorDurumuYanit.ProtoReflect.Descriptor instead.
func (*YaziyorDurumuYanit) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{6}
}

func (x *YaziyorDurumuYanit) GetBasarili() bool {
	if x != nil {
		return x.Basarili
	}
	return false
}

var File_chat_proto protoreflect.FileDescriptor

const file_chat_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"chat.proto\x12\x04chat\"J\n" +
	"\tKullanici\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x0e\n" +
	"\x02ad\x18\x02 \x01(\tR\x02ad\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\"\x97\x01\n" +
	"\x05Mesaj\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\tkullanici\x18\x02 \x01(\v2\x0f.chat.KullaniciR\tkullanici\x12\x16\n" +
	"\x06icerik\x18\x03 \x01(\tR\x06icerik\x12!\n" +
	"\x03tip\x18\x04 \x01(\x0e2\x0f.chat.MesajTipiR\x03tip\x12\x14\n" +
	"\x05zaman\x18\x05 \x01(\x03R\x05zaman\"5\n" +
	"\x10MesajGonderIstek\x12!\n" +
	"\x05mesaj\x18\x01 \x01(\v2\v.chat.MesajR\x05mesaj\".\n" +
	"\x10MesajGonderYanit\x12\x1a\n" +
	"\bbasarili\x18\x01 \x01(\bR\bbasarili\"*\n" +
	"\x11SohbetiDinleIstek\x12\x15\n" +
	"\x06oda_id\x18\x01 \x01(\tR\x05odaId\"t\n" +
	"\x12YaziyorDurumuIstek\x12\x15\n" +
	"\x06oda_id\x18\x01 \x01(\tR\x05odaId\x12-\n" +
	"\tkullanici\x18\x02 \x01(\v2\x0f.chat.KullaniciR\tkullanici\x12\x18\n" +
	"\ayaziyor\x18\x03 \x01(\bR\ayaziyor\"0\n" +
	"\x12YaziyorDurumuYanit\x12\x1a\n" +
	"\bbasarili\x18\x01 \x01(\bR\bbasarili*/\n" +
	"\tMesajTipi\x12\t\n" +
	"\x05METIN\x10\x00\x12\n" +
	"\n" +
	"\x06SISTEM\x10\x01\x12\v\n" +
	"\aYAZIYOR\x10\x022\xd0\x01\n" +
	"\n" +
	"ChatServis\x12=\n" +
	"\vMesajGonder\x12\x16.chat.MesajGonderIstek\x1a\x16.chat.MesajGonderYanit\x126\n" +
	"\fSohbetiDinle\x12\x17.chat.SohbetiDinleIstek\x1a\v.chat.Mesaj0\x01\x12K\n" +
	"\x15YaziyorDurumuGuncelle\x12\x18.chat.YaziyorDurumuIstek\x1a\x18.chat.YaziyorDurumuYanitB\x0eZ\f./proto;chatb\x06proto3"

var (
	file_chat_proto_rawDescOnce sync.Once
	file_chat_proto_rawDescData []byte
)

func file_chat_proto_rawDescGZIP() []byte {
	file_chat_proto_rawDescOnce.Do(func() {
		file_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_proto_rawDesc), len(file_chat_proto_rawDesc)))
	})
	return file_chat_proto_rawDescData
}

var file_chat_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_chat_proto_goTypes = []any{
	(MesajTipi)(0),             // 0: chat.MesajTipi
	(*Kullanici)(nil),          // 1: chat.Kullanici
	(*Mesaj)(nil),              // 2: chat.Mesaj
	(*MesajGonderIstek)(nil),   // 3: chat.MesajGonderIstek
	(*MesajGonderYanit)(nil),   // 4: chat.MesajGonderYanit
	(*SohbetiDinleIstek)(nil),  // 5: chat.SohbetiDinleIstek
	(*YaziyorDurumuIstek)(nil), // 6: chat.YaziyorDurumuIstek
	(*YaziyorDurumuYanit)(nil), // 7: chat.YaziyorDurumuYanit
}
var file_chat_proto_depIdxs = []int32{
	1, // 0: chat.Mesaj.kullanici:type_name -> chat.Kullanici
	0, // 1: chat.Mesaj.tip:type_name -> chat.MesajTipi
	2, // 2: chat.MesajGonderIstek.mesaj:type_name -> chat.Mesaj
	1, // 3: chat.YaziyorDurumuIstek.kullanici:type_name -> chat.Kullanici
	3, // 4: chat.ChatServis.MesajGonder:input_type -> chat.MesajGonderIstek
	5, // 5: chat.ChatServis.SohbetiDinle:input_type -> chat.SohbetiDinleIstek
	6, // 6: chat.ChatServis.YaziyorDurumuGuncelle:input_type -> chat.YaziyorDurumuIstek
	4, // 7: chat.ChatServis.MesajGonder:output_type -> chat.MesajGonderYanit
	2, // 8: chat.ChatServis.SohbetiDinle:output_type -> chat.Mesaj
	7, // 9: chat.ChatServis.YaziyorDurumuGuncelle:output_type -> chat.YaziyorDurumuYanit
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_chat_proto_init() }
func file_chat_proto_init() {
	if File_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_proto_rawDesc), len(file_chat_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chat_proto_goTypes,
		DependencyIndexes: file_chat_proto_depIdxs,
		EnumInfos:         file_chat_proto_enumTypes,
		MessageInfos:      file_chat_proto_msgTypes,
	}.Build()
	File_chat_proto = out.File
	file_chat_proto_goTypes = nil
	file_chat_proto_depIdxs = nil
}
