// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: chat.proto

package chat

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChatServis_MesajGonder_FullMethodName           = "/chat.ChatServis/MesajGonder"
	ChatServis_SohbetiDinle_FullMethodName          = "/chat.ChatServis/SohbetiDinle"
	ChatServis_YaziyorDurumuGuncelle_FullMethodName = "/chat.ChatServis/YaziyorDurumuGuncelle"
)

// ChatServisClient is the client API for ChatServis service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatServisClient interface {
	MesajGonder(ctx context.Context, in *MesajGonderIstek, opts ...grpc.CallOption) (*MesajGonderYanit, error)
	SohbetiDinle(ctx context.Context, in *SohbetiDinleIstek, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Mesaj], error)
	YaziyorDurumuGuncelle(ctx context.Context, in *YaziyorDurumuIstek, opts ...grpc.CallOption) (*YaziyorDurumuYanit, error)
}

type chatServisClient struct {
	cc grpc.ClientConnInterface
}

func NewChatServisClient(cc grpc.ClientConnInterface) ChatServisClient {
	return &chatServisClient{cc}
}

func (c *chatServisClient) MesajGonder(ctx context.Context, in *MesajGonderIstek, opts ...grpc.CallOption) (*MesajGonderYanit, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MesajGonderYanit)
	err := c.cc.Invoke(ctx, ChatServis_MesajGonder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServisClient) SohbetiDinle(ctx context.Context, in *SohbetiDinleIstek, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Mesaj], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChatServis_ServiceDesc.Streams[0], ChatServis_SohbetiDinle_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SohbetiDinleIstek, Mesaj]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChatServis_SohbetiDinleClient = grpc.ServerStreamingClient[Mesaj]

func (c *chatServisClient) YaziyorDurumuGuncelle(ctx context.Context, in *YaziyorDurumuIstek, opts ...grpc.CallOption) (*YaziyorDurumuYanit, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(YaziyorDurumuYanit)
	err := c.cc.Invoke(ctx, ChatServis_YaziyorDurumuGuncelle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatServisServer is the server API for ChatServis service.
// All implementations must embed UnimplementedChatServisServer
// for forward compatibility.
type ChatServisServer interface {
	MesajGonder(context.Context, *MesajGonderIstek) (*MesajGonderYanit, error)
	SohbetiDinle(*SohbetiDinleIstek, grpc.ServerStreamingServer[Mesaj]) error
	YaziyorDurumuGuncelle(context.Context, *YaziyorDurumuIstek) (*YaziyorDurumuYanit, error)
	mustEmbedUnimplementedChatServisServer()
}

// UnimplementedChatServisServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChatServisServer struct{}

func (UnimplementedChatServisServer) MesajGonder(context.Context, *MesajGonderIstek) (*MesajGonderYanit, error) {
	return nil, status.Error(codes.Unimplemented, "method MesajGonder not implemented")
}
func (UnimplementedChatServisServer) SohbetiDinle(*SohbetiDinleIstek, grpc.ServerStreamingServer[Mesaj]) error {
	return status.Error(codes.Unimplemented, "method SohbetiDinle not implemented")
}
func (UnimplementedChatServisServer) YaziyorDurumuGuncelle(context.Context, *YaziyorDurumuIstek) (*YaziyorDurumuYanit, error) {
	return nil, status.Error(codes.Unimplemented, "method YaziyorDurumuGuncelle not implemented")
}
func (UnimplementedChatServisServer) mustEmbedUnimplementedChatServisServer() {}
func (UnimplementedChatServisServer) testEmbeddedByValue()                    {}

// UnsafeChatServisServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatServisServer will
// result in compilation errors.
type UnsafeChatServisServer interface {
	mustEmbedUnimplementedChatServisServer()
}

func RegisterChatServisServer(s grpc.ServiceRegistrar, srv ChatServisServer) {
	// If the following call panics, it indicates UnimplementedChatServisServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChatServis_ServiceDesc, srv)
}

func _ChatServis_MesajGonder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MesajGonderIstek)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServisServer).MesajGonder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatServis_MesajGonder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServisServer).MesajGonder(ctx, req.(*MesajGonderIstek))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatServis_SohbetiDinle_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SohbetiDinleIstek)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChatServisServer).SohbetiDinle(m, &grpc.GenericServerStream[SohbetiDinleIstek, Mesaj]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChatServis_SohbetiDinleServer = grpc.ServerStreamingServer[Mesaj]

func _ChatServis_YaziyorDurumuGuncelle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(YaziyorDurumuIstek)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServisServer).YaziyorDurumuGuncelle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatServis_YaziyorDurumuGuncelle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServisServer).YaziyorDurumuGuncelle(ctx, req.(*YaziyorDurumuIstek))
	}
	return interceptor(ctx, in, info, handler)
}

// ChatServis_ServiceDesc is the grpc.ServiceDesc for ChatServis service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatServis_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chat.ChatServis",
	HandlerType: (*ChatServisServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MesajGonder",
			Handler:    _ChatServis_MesajGonder_Handler,
		},
		{
			MethodName: "YaziyorDurumuGuncelle",
			Handler:    _ChatServis_YaziyorDurumuGuncelle_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SohbetiDinle",
			Handler:       _ChatServis_SohbetiDinle_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "chat.proto",
}
